map $http_x_forwarded_proto $real_scheme {
    default $scheme;
    https   https;
}

server {
    listen 80;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy a la API
    location /api/ {
        proxy_pass http://dotnet-api:80/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Proxy al map service
    location /tiles/ {
        proxy_pass http://go-map-service:8082/tiles/;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $real_scheme;
    }

    location /style.json {
        proxy_pass http://go-map-service:8082/style.json;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $real_scheme;
    }
}
